# Generated by Django 4.0.4 on 2022-04-13 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Component_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant', models.CharField(blank=True, max_length=50, null=True, verbose_name='درخواست کننده')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='شرح درخواست')),
                ('StartTime', models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('CheckTime', models.DateField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('SendTime', models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('TestTime', models.DateField(blank=True, null=True, verbose_name='تاریخ تست')),
                ('EndTime', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('Progress_bar', models.IntegerField(blank=True, default='1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('Status', models.CharField(choices=[('به اتمام رسیده', 'به اتمام رسیده'), ('نامشخص', 'نامشخص'), ('رد شده', 'رد شده')], default='نامشخص', max_length=20, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تأمین قطعات',
                'verbose_name_plural': 'تأمین قطعات',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سازنده',
                'verbose_name_plural': 'سازندگان',
            },
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('Code', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='کد')),
                ('Cavities_qty', models.IntegerField(blank=True, default='1', null=True, verbose_name='تعداد حفره')),
                ('Cavities_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='شناسه حفره')),
                ('Healthy_Cavities_qty', models.IntegerField(blank=True, default='1', null=True, verbose_name='تعداد حفره های سالم')),
                ('Year', models.CharField(blank=True, max_length=40, null=True, verbose_name='سال ساخت')),
                ('Mold_qty', models.IntegerField(blank=True, default='1', null=True, verbose_name='تعداد قالب')),
                ('Material', models.CharField(blank=True, max_length=40, null=True, verbose_name='متریال طراحی')),
                ('File', models.FileField(blank=True, default='media/Default.png', null=True, upload_to='', verbose_name='فایل')),
                ('Address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='دسته بندی')),
                ('Manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer', verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'شناسنامه قالب',
                'verbose_name_plural': 'شناسنامه قالب ها',
            },
        ),
        migrations.CreateModel(
            name='Mold_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع قالب',
                'verbose_name_plural': 'نوع قالب ها',
            },
        ),
        migrations.CreateModel(
            name='Piece_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'شناسه قطعه',
                'verbose_name_plural': 'شناسه قطعه ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Repair_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant', models.CharField(blank=True, max_length=50, null=True, verbose_name='درخواست کننده')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات مشکل وارد شده')),
                ('StartTime', models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('CheckTime', models.DateField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('SendTime', models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('TestTime', models.DateField(blank=True, null=True, verbose_name='تاریخ تست')),
                ('EndTime', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('Status', models.CharField(choices=[('به اتمام رسیده', 'به اتمام رسیده'), ('نامشخص', 'نامشخص'), ('رد شده', 'رد شده')], default='نامشخص', max_length=20, verbose_name='وضعیت')),
                ('Mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mold', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'تعمیرات | اصلاحیات قالب',
                'verbose_name_plural': 'تعمیرات | اصلاحیات قالب',
            },
        ),
        migrations.CreateModel(
            name='RepairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.repair_request')),
            ],
            options={
                'verbose_name': 'تصویر مشکل',
                'verbose_name_plural': 'تصویر های مشکل',
            },
        ),
        migrations.CreateModel(
            name='Repair_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Step', models.CharField(choices=[('اول', 'اول'), ('دوم', 'دوم'), ('سوم', 'سوم'), ('چهارم', 'چهارم'), ('پنجم', 'پنجم'), ('ششم', 'ششم'), ('هفتم', 'هفتم'), ('هشتم', 'هشتم'), ('نهم', 'نهم'), ('دهم', 'دهم'), ('یازده', 'یازده'), ('دوازده', 'دوازده'), ('سیزده', 'سیزده'), ('چهارده', 'چهارده'), ('پانزده', 'پانزده'), ('شانزده', 'شانزده'), ('هفده', 'هفده'), ('هجده', 'هجده'), ('نوزده', 'نوزده'), ('بیست', 'بیست')], max_length=20, verbose_name='گام')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات عملیات تعمیر')),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.repair_request', verbose_name='برای درخواست')),
            ],
            options={
                'verbose_name': ' عملیات تعمیر ',
                'verbose_name_plural': ' عملیات تعمیرات ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name=' شماره تماس  ')),
                ('address', models.CharField(blank=True, max_length=3000, null=True, verbose_name=' آدرس  ')),
                ('user_photo', models.ImageField(blank=True, default='user_uploads/user_photo/default.png', null=True, upload_to='user_uploads/user_photo', verbose_name='تصویر کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': ' پروفایل ها ',
            },
        ),
        migrations.CreateModel(
            name='OperationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.repair_operation')),
            ],
            options={
                'verbose_name': 'تصویر عملیات',
                'verbose_name_plural': 'تصاویر عملیات',
            },
        ),
        migrations.CreateModel(
            name='MoldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.mold')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر ها',
            },
        ),
        migrations.AddField(
            model_name='mold',
            name='Piece_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.piece_id', verbose_name='شناسه قطعه'),
        ),
        migrations.AddField(
            model_name='mold',
            name='Related_product',
            field=models.ManyToManyField(related_name='Product', to='app.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.AddField(
            model_name='mold',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mold_type', verbose_name='نوع قالب'),
        ),
        migrations.CreateModel(
            name='Manufacture_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant', models.CharField(blank=True, max_length=50, null=True, verbose_name='درخواست کننده')),
                ('Progress_bar', models.IntegerField(blank=True, default='1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر آخرین وضعیت ساخت')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('StartTime', models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('CheckTime', models.DateField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('SendTime', models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('TestTime', models.DateField(blank=True, null=True, verbose_name='تاریخ تست')),
                ('EndTime', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('Status', models.CharField(choices=[('به اتمام رسیده', 'به اتمام رسیده'), ('نامشخص', 'نامشخص'), ('رد شده', 'رد شده')], default='نامشخص', max_length=20, verbose_name='وضعیت')),
                ('Mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mold', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'قالب های دردست ساخت درون سازمان',
                'verbose_name_plural': 'قالب های دردست ساخت درون سازمان',
            },
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.component_request')),
            ],
            options={
                'verbose_name': 'تصویر ساخت',
                'verbose_name_plural': 'تصاویر ساخت',
            },
        ),
    ]
