# Generated by Django 4.0.4 on 2022-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mold',
            name='Produced',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='تعداد تولید شده تا کنون'),
        ),
    ]
