# Generated by Django 4.0.4 on 2022-04-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mold_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_request',
            name='DeliveryTime',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='manufacture_request',
            name='DeliveryTime',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='repair_request',
            name='DeliveryTime',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
