# Generated by Django 4.0.4 on 2022-04-13 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_repair_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outside_Manufacture_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant', models.CharField(blank=True, max_length=50, null=True, verbose_name='درخواست کننده')),
                ('Manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='سازنده')),
                ('Progress_bar', models.IntegerField(blank=True, default='1', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('Image', models.ImageField(blank=True, default='media/Default.png', null=True, upload_to='media', verbose_name='تصویر آخرین وضعیت ساخت')),
                ('Description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('StartTime', models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('ContractTime', models.DateField(blank=True, null=True, verbose_name='تاریخ قرارداد')),
                ('DeliveryTime', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('ApproveTime', models.DateField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('Status', models.CharField(choices=[('به اتمام رسیده', 'به اتمام رسیده'), ('نامشخص', 'نامشخص'), ('رد شده', 'رد شده')], default='نامشخص', max_length=20, verbose_name='وضعیت')),
                ('Mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mold', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'قالب های دردست ساخت برون سازمان',
                'verbose_name_plural': 'قالب های دردست ساخت برون سازمان',
            },
        ),
    ]
